version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: monetrix_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-monetrix}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monetrix_network

networks:
  monetrix_network:
    driver: bridge

volumes:
  postgres_data:
